getwd()
setwd("/Users/eylulaygun/Desktop/Year\ 5/stat\ 447B/CovidSentimentAnalysis")


# read dataframe and perform basic transformations
df <- read.csv("updated_dataframe-apr06.csv")

# Create new variable: popularity score
# this will be our response variable for the rest of project
# Intuitively, growth in reach generated by retweets is not linear but exponential (just like spreading covid!),
# and with slight increments in retweets we can still achieve large increases in the reach of a tweet, which is what makes it popular
# eg. avg twitter user has ~200 followers. 
#     If avg user tweets something, for each retweet they get,
#     their tweet will be visible in ~200 other users feed. (assuming no overlap between followers)
df$popularity_score <- 0.75*(df$retweets) + 0.25*(df$favorites)
print(summary(df$popularity_score))
df$popularity_score_ctg <- cut(df$popularity_score, breaks = c(-0.1, 1, 9.9, 1000), labels = c("LOW", "AVG", "HIGH"))


# new columns, explanatory variables:
df$date <- as.POSIXct(df$date,tz=Sys.timezone(), format ="%Y-%m-%d") # remove H-M-Sec from date
# new column, turn compound score to ordinal categorical 
df$overall_sentiment <- cut(df$compound_score, breaks = c(-1, -0.05, 0.05, 1), labels =  c("NEG", "NEU", "POS"))


# save new csv 
write.csv(df, "01b-updated_dataframe-apr06.csv")
