library(mlbench)
library(VGAM)
library(rpart) 
library(rpart.plot) 
library(randomForest)

library(VGAM)

getwd()
setwd("/Users/eylulaygun/Desktop/Year\ 5/stat\ 447B/CovidSentimentAnalysis")

# read dataframe and perform basic transformations
df <- read.csv("updated_dataframe-apr06-2.csv", stringsAsFactors = T)
training_set <- read.csv("training_set.csv", stringsAsFactors = T)
testing_set <- read.csv("testing_set.csv", stringsAsFactors = T)

# Create new variable: popularity score
# this will be our response variable for the rest of project
# Intuitively, growth in reach generated by retweets is not linear but exponential (just like spreading covid!),
# and with slight increments in retweets we can still achieve large increases in the reach of a tweet, which is what makes it popular
# eg. avg twitter user has ~200 followers. 
#     If avg user tweets something, for each retweet they get,
#     their tweet will be visible in ~200 other users feed. (assuming no overlap between followers)
training_set$popularity_score = (0.75*(training_set$retweets^(1/4)) + 0.25*(training_set$favorites^(1/4)))
# new column, turn compound score to ordinal categorical 
training_set$popularity_score_ctg <- cut(training_set$popularity_score, breaks = c(-0.01, 0.2, 1, 1.75, 690), labels =  c("NO", "AVG", "YES", "VYES"))
plot(training_set$popularity_score, training_set$compound_score)
summary(training_set$popularity_score)

plot(table(training_set$popularity_score_ctg))

training_set$retweets_inv <- 1/ (training_set$retweets  +1 )
training_set$retweets_ctg <- cut(training_set$retweets, breaks = c(-0.01, 0.5, 1, 5, 1000), labels =  c("NO", "AVG", "YES", "VYES"))
table(training_set$retweets_ctg)
plot(table(training_set$retweets_ctg))


summary(training_set$retweets)
summary(training_set$favorites)


#### initial model


plot(log(1/(0.1 + training_set$retweets)))
plot(training_set$retweets)

logit1= glm(retweets_ctg ~ hashtags_count + compound_score + overall_sentiment,family=binomial(link="logit"),data=training_set)
summary(logit1)

lm1 <- lm(retweets_inv ~ hashtags_count  + overall_sentiment + user_verified , data = training_set)
summary(lm1)


model2 <- rpart(retweets_ctg ~ hashtags_count + compound_score + overall_sentiment, data=training_set)   
par(mfrow=c(1,1))
rpart.plot(model2, box.palette = "blue") 
tree_out_pred =predict(model2,newdata=testing_set)

boxplot(training_set$hashtags_count, training_set$retweets_ctg)

labels =  c("NO", "AVG", "YES", "VYES")
par(mfrow=c(2,2))
for (i in 1:4){
  sentiment_i_hashtags = training_set$hashtags_count[which(training_set$retweets_ctg == labels[i])]
  sentiment_i_scores = training_set$compound_score[which(training_set$retweets_ctg == labels[i])]
  print(head(sentiment_i_scores))
  print(labels[i])
  boxplot(sentiment_i_hashtags, xlab = labels[i], ylab= "# of hashtags")
}


